[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
rnd_anchor_framework = "FZkMHQsM2ELE7baJvWJfZcL9cZFdWWNVPCqV2Fz1Eb7u"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/skippcode/solana_projects/rust-program-research/rnd_anchor_framework/rnd933Ypd2oq9b8VBy3xLRE73C6Q7nDq2m9xzHU3h3Q.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
